export const ADD_LISTING_LOADING = 'ADD_LISTING_LOADING'
export const ADD_LISTING_SUCCESS = 'ADD_LISTING_SUCCESS'
export const ADD_LISTING_ERROR = 'ADD_LISTING_ERROR'

export const FETCH_LISTING_LOADING = 'FETCH_LISTING_LOADING'
export const FETCH_LISTING_SUCCESS = 'FETCH_LISTING_SUCCESS'
export const FETCH_LISTING_ERROR = 'FETCH_LISTING_ERROR'

export const FETCH_ALL_LISTING_LOADING = 'FETCH_ALL_LISTING_LOADING'
export const FETCH_ALL_LISTING_SUCCESS = 'FETCH_ALL_LISTING_SUCCESS'
export const FETCH_ALL_LISTING_ERROR = 'FETCH_ALL_LISTING_ERROR'

export const EDIT_LISTING_LOADING = 'EDIT_LISTING_LOADING'
export const EDIT_LISTING_SUCCESS = 'EDIT_LISTING_SUCCESS'
export const EDIT_LISTING_ERROR = 'EDIT_LISTING_ERROR'

export const DELETE_LISTING_LOADING = 'DELETE_LISTING_LOADING'
export const DELETE_LISTING_SUCCESS = 'DELETE_LISTING_SUCCESS'
export const DELETE_LISTING_ERROR = 'DELETE_LISTING_ERROR'

export const FETCH_PROPERTY_TYPE_LOADING = 'FETCH_PROPERTY_TYPE_LOADING'
export const FETCH_PROPERTY_TYPE_SUCCESS = 'FETCH_PROPERTY_TYPE_SUCCESS'
export const FETCH_PROPERTY_TYPE_ERROR = 'FETCH_PROPERTY_TYPE_ERROR'

export const FETCH_CATEGORY_LOADING = 'FETCH_CATEGORY_LOADING'
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS'
export const FETCH_CATEGORY_ERROR = 'FETCH_CATEGORY_ERROR'

export const FETCH_LISTING_TYPE_LOADING = 'FETCH_LISTING_TYPE_LOADING'
export const FETCH_LISTING_TYPE_SUCCESS = 'FETCH_LISTING_TYPE_SUCCESS'
export const FETCH_LISTING_TYPE_ERROR = 'FETCH_LISTING_TYPE_ERROR'

export const CLEAR_CURRENT_LISTING = 'CLEAR_CURRENT_LISTING'
export const SET_CURRENT_LISTING = 'SET_CURRENT_LISTING'